server.port: 9101

spring:
  application.name: demo-config-server
  cloud.config:
    server.git:
      uri: file://${user.home}/centralize-config-depot
      default-label: master

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
    registryFetchIntervalSeconds: 1
  instance:
    leaseRenewalIntervalInSeconds: 1
