server:
  port: 9443


spring:
  application.name: spring-template-demo
 
  
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9001/eureka}
    registryFetchIntervalSeconds: 1
  instance:
    hostname: localhost
    #secure-port-enabled: true
    #non-secure-port-enabled: false
    #preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    #nonSecurePortEnabled: false
    #securePortEnabled: true
    #statusPageUrl: https://${eureka.hostname}:${server.port}/actuator/info
    #healthCheckUrl: https://${eureka.hostname}:${server.port}/health
    #homePageUrl: https://${eureka.hostname}:${server.port}/
